### ISSUE TITLE
Add review and rating logic

### ISSUE THREAD

**Issue by UO283216** [Arquisoft/lomap_en2a#100]
Be able to leave a review (date,title,body and user posting it) in a location (it can be mine or one of my friends' ones). Each user can give 1 rating to a  location. The avg of that ratings (1 to 5 in a ⭐ format) will be displayed on the location.

**Comment by UO283216** [comment]
By now view of the review is implemented and the non persistent way of adding the review is almost there. @garciafdezpatricia  is implementing the way of persisting the updates of the locations (the addition of a rating or a review updates the location to add it)

**Comment by UO283216** [comment]
For the implementation of the reviews and in order to ensure a user can not give a review twice to the same location i will be modifying the starting data type (array of ints) to a map of <webId,int>. This way we can retrieve the necessary information to identify if a user has given a review and also the avg rating can be computed.
This will surely give problems on how to save it on pod @garciafdezpatricia  🤦

**Comment by garciafdezpatricia** [comment]
Do you mean the score or the review data type?

**Comment by UO283216** [comment]
The rating (⭐) will be a map <WebId (string),int> to allow unique rate by user.
The review will be as we already indicated (removing the username since it is redundant).

**Comment by UO283216** [comment]
UPDATE.
The local version is working besides the session info that I am currently trying to make it global so we do not have to pass it as a prop to EVERY component. I expect to have it working for tomorrow.

**Comment by UO283216** [comment]
UPDATE
Solved both of the issues. To use the session we just have to use the useSession() method on the class ant the package of inrupt will load the loaded session for us. 
I also completed the reviewing and rating system in local (without storing in pod) using the information of the session.

**Comment by garciafdezpatricia** [comment]
Review and rating system stored now in pod. No problems neither to retrieve nor add
