### ISSUE TITLE
Image size problem

### ISSUE THREAD

**Issue by UO283216** [Arquisoft/lomap_en2a#104]
For small images as the ones we all have been using to test the locations all works fine but the problem is that images in Base64 (format we are currently using to store all images ) increases the size in a 140% [(Ref).](https://es.wikipedia.org/wiki/Base64#:~:text=.%20De%20esta%20manera%2C%20el%20tama%C3%B1o%20real%20de%20los%20datos%20codificados%20conforme%20a%20MIME%20suele%20ser%20de%20un%20140%25%20del%20tama%C3%B1o%20original.) This makes a HUGE difference when dealing with images that are are bigger than the ones we are using to test (200x200). 

I believe this is bad news for our architecture and we must come up with a solution to it. Two approaches available as I see it:
- Give a 200x200 (or byte size maximum) for the input files -> this can be done as a counter meassure by now 
- Change implementation to use in the Location type the Array<File> type for the images. And then when saving the image we can do 
```
const imageThing = createThing({
  url: datasetUrl,
  name: file.name,
  contentType: file.type,
  body: file,
});
```
- Another alternative is to compress the images before to save them eather in Base64 (could give us some margin right now) or in File format (will be the optimum way of approaching this issue if available).

**Comment by UO282365** [comment]
Pull request #153
