### ISSUE TITLE
Self report third deliverable

### ISSUE THREAD

**Issue by garciafdezpatricia** [Arquisoft/lomap_en2a#116]

**Comment by garciafdezpatricia** [comment]
For this deliverable, I did:
#74 Store images in a location
#86 Create locations inside folder in pod
#91 Assign UUID to locations
#96 Filter locations by categories
#100 Add review and rating logic along @UO283216 
#109 Grant and revoke access to friends 
Also restructured the pod folder hierarchy

**Comment by UO282365** [comment]
For this deliverable, I've worked in:
- #72 
- #110 
- #100 (Solved bugs)
