### ISSUE TITLE
Perform Cucumber 🥒 tests for ALL the views

### ISSUE THREAD

**Issue by UO283216** [Arquisoft/lomap_en2a#134]
This must be done ASAP since it was meant for previous deliverable and now has to include the new views appearing for this other deliverable.

**Comment by garciafdezpatricia** [comment]
all views done. Details:
- The functionality of deleting locations wont be tested using cucumber since it takes a lot of time and can be more efficently tested in unit testing.
- Added a test for each view of the application.
