### ISSUE TITLE
Allow the user to delete a review?

### ISSUE THREAD

**Issue by garciafdezpatricia** [Arquisoft/lomap_en2a#136]

**Comment by UO283216** [comment]
Seems interesting to allow writting user to delete review, it should not be that dificult

**Comment by garciafdezpatricia** [comment]
Done, visual effects missing to get the best usability

**Comment by garciafdezpatricia** [comment]
the reviews are deleted when you click on the button and the component is re renderized. However, if you click on the list of locations and then on the same location, the review appears. If you recharge the page the review does not appear (solid detele is working properly). 
Check the implementation of the location info

**Comment by garciafdezpatricia** [comment]
Fixed bug -> added loadLocations() after a review was deleted. Change the ReviewSection to be inside the LocationInfo function so loadlocations() can be called without having to pass down another parameter
