### ISSUE TITLE
Create slides for presentation

### ISSUE THREAD

**Issue by UO283216** [Arquisoft/lomap_en2a#180]

**Comment by garciafdezpatricia** [comment]
https://www.canva.com/design/DAFhk8P6mL8/erP4fSRHNblGv1n_fTqObQ/edit?utm_content=DAFhk8P6mL8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton 

The chosen template is just an option, it was the most 'professional' one, you can change it if you want

**Comment by UO283216** [comment]
Looks fine to me, I will be leaving here a list of things that must be done in the presentation so we do not miss any.
- [ ] Add usability stats to the presentation (Satisfaction graphs and also add references to the usability issues open)
- [ ] Add load testing results, both the Gatling result page reference and the Apache Benchmark results (ab)

**Comment by garciafdezpatricia** [comment]
Done
