### ISSUE TITLE
Self report - Final delivery

### ISSUE THREAD

**Issue by garciafdezpatricia** [Arquisoft/lomap_en2a#198]

**Comment by SantiFC12** [comment]
For this delivery I worked on:
* #121 
* #179 , #194 and #195 (in the end we weren't able to merge it)
* #196 
* #186 
* #176 
* #175 
* #142 
* #134 the beginning of the tests and some fixes in the end

**Comment by UO282365** [comment]
Self report final deliverable.
 
- #183
- #182
- #181
- #145
- #144
- #133
- #104
- #186
- General and on-the-go bugs from the application.

**Comment by garciafdezpatricia** [comment]
For this delivery:

- #122 
- #123 
- #125 
- #126 
- #127 
- #134 made ALL cucumber tests
- #136 
- #138 
- #140 
- #141 
- #147 
- #155 
- #162 
- #165 
- #173 
- #175 
- #180 made ALL the slides (except the addition of the runtime schemas)
- #186 
- #187 
- #189

**Comment by UO283216** [comment]
Improved application by implementing
- #130 
- #133 with the help of @UO282365 
- #146 
- #154 
- #158 
- #159 
- #161 
- #164 
- #168 
- #169 
- #171
