### ISSUE TITLE
Self report's for the second deliverable - Prototype release

### ISSUE THREAD

**Issue by UO283216** [Arquisoft/lomap_en2a#68]

**Comment by garciafdezpatricia** [comment]
Location View #58 Display the location information when click on a marker in the map
Profile View #57 Display the profile when click on profile button in the menu
Basic Pod Operations (Read, Write and Login) #48 
Change mindmap section 10 #44 Fix 1st version of documentation
Change ARD Link in section 9 #45 Fix 1st version of documentation

**Comment by UO282365** [comment]
Friends view.(displaying the list of Friends and an input for adding)
Friends functionality.(retrieving Friends and adding Friends from the pod)

**Comment by UO283216** [comment]
For this deliverable I implemented the following functionallity:
#47  -> Map implementation with  @SantiFC12 
#47 -> Addition of the list of locations
#55  -> Backend and frontend connection (To be continued)
#56 -> Menu addition

I also contributed to solve team member's problems by means of team calls where 'pair programming' was done.
